### PR TITLE
Fix paradigm audio

### LINKED ISSUE #636: Potentially unexpected/undesirable behavior for presentation of speech
-------- Forwarded Message --------
Subject: 	Re: Bug in Itwewina webpage?
Date: 	Fri, 29 Jan 2021 19:50:11 +0000
From: 	Theron Neilson <to.give.out@outlook.com>
To: 	altlab+itwewina@ualberta.ca <altlab+itwewina@ualberta.ca>

There may also be a bug if you click on the "show more" again after it shows more once.  Same page as other bug.

--Theron
From: Theron Neilson
Sent: January 29, 2021 1:35 PM
To: altlab+itwewina@ualberta.ca <altlab+itwewina@ualberta.ca>
Subject: Bug in Itwewina webpage?
 
Hi,

On https://sapir.artsrn.ualberta.ca/cree-dictionary/word/itw%C3%AAwin/ :

When I click on the "show more" button for the word variants for "itwêwin", the "play pronunciation" components of the web page disappear.  Is this intentional?

I observed this behavior in both Firefox and Microsoft Edge.  Have not tested this for any other words.

Thanks,

Theron

### PR DESCRIPTION
**Pull request by nienna73**
Fix #636 . Instead of replacing entire word details page when pressing "load more", just replace the paradigm section.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -198,12 +198,12 @@ function setupParadigmSizeToggleButton() {
         }
         window.history.replaceState({}, document.title, updateQueryParam('paradigm-size', nextParadigmSize))
         const oldParadigmNode = document.getElementById('paradigm')
-        oldParadigmNode.parentElement.replaceChild(paradigmFrag, oldParadigmNode)
+        oldParadigmNode.firstElementChild.replaceWith(paradigmFrag)
```
Comment (andrewdotn) [inline src/index.js:201]: This may be less brittle going forward if the relevant node is specified using a name, such as a new CSS selector

    oldParadigmNode.querySelector('.paradigmTableOrSomething').replaceWith

**Review by andrewdotn — APPROVED** [review]
